name: Generate PDF from Markdown

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF
        run: |
          pandoc cv.md -o cv.pdf --pdf-engine=xelatex -V geometry:margin=1in

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        
      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_Personal_Access_Token }}
        run: |
          git add cv.pdf
          git commit -m "Automated PDF update on $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git push --quiet origin ${{ github.ref_name }}